### ISSUE TITLE
Laravel 11 support 

### ISSUE THREAD

**Issue by joseederangojr** [goedemiddag/betterstack-logs#1]
add support for laravel version 11

**Comment by dvdheiden** [comment]
Hi! 

Thank your for your issue. We already talked about it and will be upgrading this package soon.

**Comment by johankrijt** [comment]
@joseederangojr Will look into it next week, thanks for bringing it to our attention.

**Comment by joseederangojr** [comment]
Awesome! For now I'm just using my fork to use v11 monkey-patching with composer until a official version is released

**Comment by dvdheiden** [comment]
I'm pleased to inform you that we just released version 1.1.0 which has Laravel 11 compatibility. Happy logging!
